build:
  cuda_version: "12.1.1"
  system_packages:
    - "ffmpeg"
  python_packages:
    - "git+https://github.com/huggingface/transformers.git"
    - "accelerate"
    - "qwen-omni-utils[decord]"
    - "torchvision"
    - "inferless==0.2.13"
    - "pydantic==2.10.2"
